@api = http://localhost:5000

POST {{api}}/usuario/creaUsuarioAlumno
Content-Type: application/json

        {
            "id":"1",
            "nombre": "a1",
            "apellido": "aa",
            "email": "a1@uni.pe",
            "clave": "qwer",
            "telefono":"123"
        }

###

POST {{api}}/usuario/iniciaSesion
Content-Type: application/json

        {
            "email": "p@fds.cc",
            "clave": "qwer"
        }

###
